#include "util/set-inter/emptyheaded/include/utils/utils.hpp"
#include "util/set-inter/emptyheaded/include/intermediate/intermediate.hpp"
#include "Encoding.hpp"
#include "TrieIterator.hpp"
#include "TrieBuilder.hpp"
#include "Trie.hpp"
#include "util/set-inter/emptyheaded/include/trie/TrieBlock.hpp"