# find sse/avx2/avx512 cpu-flags
include(FindSSE)
if (AVX2_FOUND)
    option(AVX2 "enable AVX2" ON)
    set(AVX2 ON)
    set(AVX ON)
    set(SSE4 ON)
elseif (AVX_FOUND)
    message("found AVX")
    set(AVX ON)
    set(SSE4 ON)
elseif (SSE4_1_FOUND)
    message("found sse4.1")
    set(SSE4 ON)
elseif (SSE2_FOUND)
    message("found sse2")
endif ()
if (KNL)
    message(KNL)
endif ()
if (AVX2)
    message(AVX2)
endif ()
if (AVX)
    message(AVX)
endif ()
if (SSE4)
    message(SSE4)
else ()
    message(NO_SSE4_EVEN)
endif ()