# Automated Windows (MSVC++) testing using appveyor.com
# https://ci.appveyor.com/projects

version: 1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2017

platform:
  - x86
  - x64

build_script:
  - if "%platform%" == "x86" cmake -G "Visual Studio 15 2017" .
  - if "%platform%" == "x64" cmake -G "Visual Studio 15 2017 Win64" .
  - cmake --build . --config Release

test_script:
  - ctest -C Release
